### PR TITLE
Pin wandb version in llm-finetuning repo

### PR DESCRIPTION
**Pull request by yirenlu92**
- need to pin wandb version, otherwise get this error: https://github.com/wandb/wandb/issues/7406

### CODE REVIEW

**Comment by mwaskom** [comment]
Ah nice, this bit me when I updated the Axolotl container version and I (falsely) attributed it to that.

I don't immediately understand why CI is failing but it seems not great?

**Comment by yirenlu92** [comment]
oof yeah that is a lot of failing tests

**Comment by mwaskom** [comment]
oh you deleted `src/inference.py` by accident :D

**Comment by yirenlu92** [comment]
🤦‍♀️ sorry I had some local changes that I didn't want to include and forgot about that.

**Comment by charlesfrye** [comment]
pulled this change into #48

**Pull request closed without merging**
